<?php

/** @var \AHT\ShopByBrand\Block\Frontend\Brand\Index $block */
$brands = $block->showBrandCollection()->getData();
$namesearch = $block->getRequest()->getParam('name');
$sort = $block->getRequest()->getParam('orderby');

$asc = ($sort == 'ASC') ? 'selected' : null;
$desc = ($sort == 'DESC') ? 'selected' : null;
?>
<h2>Listing Brands</h2>
<form action="">
    <div class="search">
        <input class="name" type="text" name="name" placeholder="Tìm kiếm theo tên" value="<?php echo $namesearch ?>"><br>
        <input class="action subscribe primary" type="submit" value="Tìm kiếm">
    </div>

    <select onchange="this.form.submit()" name="orderby" id="cars">
        <option value="">Sắp xếp theo:</option>
        <option <?php echo $asc ?> value="ASC">A-Z</option>
        <option <?php echo $desc ?> value="DESC">Z-A</option>
    </select>
</form>
<a href="<?php echo $this->getURL('brand/brand/index'); ?>"></a>
<ul class="list-brand">
    <?php foreach ($brands as $key => $value) :; ?>
        <?php
        $urlById = $this->getURL('brand/brand/detail')."id/". $value['brand_id'];
        $name = $value['name'];
        $image = $value['image'];
        ?>
        <li class="brand-item"><a href="<?php echo $urlById; ?>">
                <div class="">
                    <div class="image">
                        <img src="<?php echo $image; ?>" alt="">
                    </div>
                    <p class="name"><?php echo $name; ?></p>
                </div>
            </a>
        </li>
    <?php endforeach; ?>
</ul>




<div class="component-wrapper">
    <div class="field">
        <label class="label" for="email"><span data-bind="i18n: 'Tạo người dùng mới'"></span></label>
        <div class="control">
            <input name="customername"
                   id="customername"
                   type="text"
                   class="input-text"
                   data-bind="value: customerData">
        </div>
    </div>
    <div class="primary">
        <button type="button" class="action action-login secondary" data-bind="click: addNewCustomer">
            <span data-bind="i18n: 'Lưu'"></span>
        </button>
    </div>
 
    <div class="customer-list" style="width: 20%;background: #eee;margin-top: 10px;" data-bind="foreach: customerName">
        <li data-bind="text: name"></li>
    </div>
</div>


