<?php

/** @var \AHT\ShopByBrand\Block\Frontend\Brand\Showbrand $block */
$brand = $block->showBrandByProductID();
$display = 'flex';
if ($brand != null) {
    $status = $brand[0]['display'];

    if ($status == "showname") {
        $image = '';
    } else {
        $image =  $brand[1]['image'];
        $image = ($image != "") ? '<div class="img"><img src="' . $image . '" alt=""> </div>' : "Không có ảnh";
    }

    if ($status == "showimage") {
        $name = '';
    } else {
        $name = $brand[1]['name'];
        $name = '<div class="name">' . $name . '</div>';
    }
} else {
    $display = 'none';
    $image = '';
    $name = '';
}
?>

<style>
    .brand{
        display: flex;
        flex-direction: column;
        align-items: center;
        width: 30%;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.4);
    }

    .brand .img {
        width: 100%;
        height: 100%;
    }
    .brand .name {
        font-size: 30px;
        font-weight: bold;
    }

</style>

<div class="brand" style="<?php echo $display; ?>">
    <?php echo $image; ?>
    <?php echo $name; ?>
</div>