<?php

/** @var \AHT\ShopByBrand\Block\Frontend\Brand\BrandInProduct $block */
$brand = $block->showBrandByProductID();
?>

<style>
    .brand {
        flex-direction: column;
        align-items: center;
        width: 30%;
        padding: 20px;
        border-radius: 10px;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.4);
    }

    .brand .img {
        width: 100%;
        height: 100%;
    }

    .brand .name {
        font-size: 30px;
        font-weight: bold;
    }
</style>

<?php if($block->isEnable()): ?>
<div class="brand">
    <?php if ($block->isShowImage() || $block->isShowAll() && $brand->getImage()) : ?>
        <div class="img"><img src="<?php echo $brand->getImage(); ?>" alt=""></div>
    <?php endif ?>

    <?php if ($block->isShowName() || $block->isShowAll() && $brand->getName()) : ?>
        <div class="name"><?php echo $brand->getName(); ?></div>
    <?php endif ?>
</div>
<?php endif; ?>