<?php
/** @var \AHT\Blog\Block\Frontend\Blog\Index $block */
    $blog = $block->getBlogByID()[0];
    $image = ($blog['image'] != '') ? "<img class='img' src=".$blog['image']." alt=''>" : "Không có hình ảnh";
?>
<style>
    .content-detail {
        display: flex;
        justify-content: space-around;
    }
    .left {
        text-align: center;
    }
    .left .name{
        font-size: 20px;
        font-weight: bold;
        margin-top: 10px;
    }
    .img {
        width: 150px;
        height: 150px;
        border: 1px solid #333;
        border-radius: 50%;
        overflow: hidden;
        display: flex;
        align-items: center;
        justify-content: center;
    }
    .left .img img{
        width: 100%;
        height: 100%;
    }
    .blog_dan_detail{
        list-style: none;
        display: flex;
        flex-direction: column;
    }
    .blog_dan_detail li {
        display: flex;
    }
    .blog_dan_detail img{
        width: 80px;
        height: 80px;
    }
    .blog_dan_detail li a{
        text-decoration: underline;
    }
</style>
<div class="content-detail">
    <ul class="blog_dan_detail">
        <li><h3>Detail about <a href=""><?php echo $blog['name']?></a> blog</h3></li>
        <li>Name: <?php echo $blog['name']?></li>
        <li>Image: <?php echo $image?></li>
        <li>Short description: <?php echo $blog['short_description']?></li>
        <li>Description: <?php echo $blog['description']?></li>
        <li>Tag: <?php echo $blog['tag']?></li>
        <li>Url: <?php echo $blog['url']?></li>
        <li>Author: <?php echo $blog['author']?></li>
        <li>Created at: <?php echo $blog['created_at']?></li>
        <li>Updated at: <?php echo $blog['updated_at']?></li>    
    </ul>
    <div class="left">
        <div class="img"><?php echo $image; ?></div>
        <div class="name"><?php echo $blog['name']?></div>
    </div>
</div>