<?php
/** @var \AHT\Blog\Block\Frontend\Blog\Index $block */
$dataBlogCollection = $block->getCollectionBlog();
?>
<h3>All blogs</h3>
<ul>
    <?php foreach ($dataBlogCollection as  $blog) : ?>
        <?php 
            echo $urlRequest = "blog/blog/".$blog->getUrl_key();
            $urlTarget  = "blog/blog/detail/blog_id/".$blog->getBlog_id();
        ?>
        <li>
            <a href="<?php echo $block->getBaseUrl().$urlTarget; ?>">
                <?php echo $blog->getName(); ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>

<?php if ($block->getPagerHtml()) :;?>
    <div class="order-products-toolbar toolbar bottom" ><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>


