<?php

/** @var \AHT\Blog\Block\Frontend\Blog\Index $block */



$dataBlogCollection = $block->getCollectionBlog();
?>
<h3>All blogs</h3>
<ul>
    <?php foreach ($dataBlogCollection as  $blog) : ?>
        <!-- //Prepare for rewrite URL -->
        <?php
            $urlRequest = $block->getBlogUrl($blog);
            $urlTarget  = $block->getBaseUrl()."blog/blog/detail/blog_id/" . $blog->getBlog_id();
            $name = $blog->getName();
        ?>

        <li>
            <a href="<?php echo $urlRequest; ?>">
                <?php echo $name; ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>

<?php if ($block->getPagerHtml()) :; ?>
    <div class="order-products-toolbar toolbar bottom"><?php echo $block->getPagerHtml(); ?></div>
<?php endif ?>