<?php

/** @var \AHT\Blog\Block\Template $block */
$dataBlogCollection = $block->getCollectionCategory();
?>
<h3>All categories</h3>
<ul>
    <?php foreach ($dataBlogCollection as  $itemUic) : ?>
        <li>
            <a href="<?php echo $block->getUrl(); ?>category/<?php echo $itemUic->getName().'.html'; ?>">
                <?php echo $itemUic->getName(); ?>
            </a>
        </li>
    <?php endforeach; ?>
</ul>