<?php

/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block AHT\Test\Block\Index\Index */

$testCollection = $block->getList();
?>

<a href="<?= $block->getBaseUrl() ?>hello/index/create">Them moi</a>

<table>
    <thead>
        <tr>
            <th>ID</th>
            <th>Name</th>
            <th>Des</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($testCollection as $key => $test) : ?>
            <tr>
                <td><?= $test->getTest_id() ?></td>
                <td><?= $test->getName() ?></td>
                <td><?= $test->getDes() ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>